package br.com.fean.si.poo2.projetounikahair.exemplos;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.SpringLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jordan
 */
public class PainelCRUDGenerico extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form PainelGenerico
     */
    protected JPanel paiTopo = new JPanel();
    protected JPanel paiModulo = new JPanel();
    protected JPanel paiPesquisa = new JPanel();
    protected JPanel paiFormulario = new JPanel();
    protected JPanel paiTabela = new JPanel();
    protected JPanel paiBotoes = new JPanel();
    protected JPanel paiCentral = new JPanel();
    
    public PainelCRUDGenerico() {
        
        initComponents();
        setLayout(new BorderLayout());
        //BORDER NORTE
        //paiModulo.setBackground(Color.blue);
        paiPesquisa.setBackground(Color.blue);
        paiPesquisa.setLayout(new FlowLayout(FlowLayout.RIGHT));
        paiTopo.setLayout(new BoxLayout(paiTopo, BoxLayout.Y_AXIS));
        paiTopo.add(paiModulo);
        paiTopo.add(paiPesquisa);
        

        //BORDER CENTRO
        paiTabela.setLayout(new FlowLayout());        
        paiFormulario.setLayout(new SpringLayout());
        paiFormulario.setBackground(Color.blue);
        paiCentral.setLayout(new BoxLayout(paiCentral, BoxLayout.Y_AXIS));
        paiCentral.add(paiTabela);
        paiCentral.add(paiFormulario);
        
        //BORDER SUL
        paiBotoes.setLayout(new FlowLayout(FlowLayout.RIGHT));
        paiBotoes.setBackground(Color.BLUE); 
        
        
        add(paiTopo,BorderLayout.NORTH);
        add(paiCentral,BorderLayout.CENTER);
        add(paiBotoes,BorderLayout.SOUTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
